name = "editor"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"

assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
#observability = { enabled = "true" }

[env.dev]
name = "editor-develop"

[vars]
PUBLIC_ALLMAPS_API_WS_URL = "wss://dev.api.allmaps.org"
PUBLIC_ALLMAPS_API_URL = "https://dev.api.allmaps.org"
PUBLIC_ALLMAPS_ANNOTATIONS_API_URL = "https://dev.annotations.allmaps.org"
PUBLIC_ALLMAPS_PREVIEW_URL = "https://dev.preview.allmaps.org/apps/editor"
PUBLIC_ALLMAPS_VIEWER_URL = "https://dev.viewer.allmaps.org"
PUBLIC_ALLMAPS_TILE_SERVER_URL = "https://allmaps.xyz"
PUBLIC_EXAMPLES_API_URL = "https://sammeltassen-allmaps.web.val.run"
PUBLIC_STATS_WEBSITE_ID = ""

[env.dev.vars]
PUBLIC_ALLMAPS_API_WS_URL = "wss://dev.api.allmaps.org"
PUBLIC_ALLMAPS_API_URL = "https://dev.api.allmaps.org"
PUBLIC_ALLMAPS_ANNOTATIONS_API_URL = "https://dev.annotations.allmaps.org"
PUBLIC_ALLMAPS_PREVIEW_URL = "https://dev.preview.allmaps.org/apps/editor"
PUBLIC_ALLMAPS_VIEWER_URL = "https://dev.viewer.allmaps.org"
PUBLIC_ALLMAPS_TILE_SERVER_URL = "https://allmaps.xyz"
PUBLIC_EXAMPLES_API_URL = "https://sammeltassen-allmaps.web.val.run"
PUBLIC_STATS_WEBSITE_ID = ""
